spring.application.name=roadlines

# database connection 
spring.datasource.url =jdbc:mysql://localhost:3306/sachdeva_roadlines
spring.datasource.username =root
spring.datasource.password =Vicky420@#

spring.datasource.driver-class-name =com.mysql.cj.jdbc.Driver

spring.jpa.show-sql =true
spring.jpa.hibernate.ddl-auto =update


# JWT Token creation 
jwt.security.key = ${JWT_SECURITY_KEY}

# Context path
server.servlet.context-path =/api/v1
